const skills ={
    1: {
        skill: 'HTML5',
        pic: './assets/images/skills/HTML5.png',
        link: 'https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5',
        listClass: 'liHTML5',
    },
    2: {
        skill: 'CSS3',
        pic: './assets/images/skills/CSS3.png',
        link: 'https://developer.mozilla.org/en-US/docs/Archive/CSS3',
        listClass: 'liCSS3',
    },
    3: {
        skill: 'ES6',
        pic: './assets/images/skills/ES6.png',
        link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
        listClass: 'liES6',
    },
    4: {
        skill: 'NodeJs',
        pic: './assets/images/skills/NodeJs.png',
        link: 'https://nodejs.org/en/',
        listClass: 'liNodeJs',
    },
    5: {
        skill: 'npm',
        pic: './assets/images/skills/npm.png',
        link: 'https://www.npmjs.com/',
        listClass: 'liNPM',
    },
    6: {
        skill: 'React',
        pic: './assets/images/skills/ReactJs.png',
        link: 'https://reactjs.org/',
        listClass: 'liReact',
    },
    7: {
        skill: 'jQuery',
        pic: './assets/images/skills/jQuery.png',
        link: 'https://jquery.com/',
        listClass: 'lijQuery',
    },
    8: {
        skill: 'MongoDB',
        pic: './assets/images/skills/MongoDB.png',
        link: 'https://www.mongodb.com/',
        listClass: 'liMongoDB',
    },
    9: {
        skill: 'Mongoose',
        pic: './assets/images/skills/Mongoose.png',
        link: 'https://mongoosejs.com/',
        listClass: 'liMongoose',
    },
    10: {
        skill: 'MySQL',
        pic: './assets/images/skills/MySQL.png',
        link: 'https://www.mysql.com/',
        listClass: 'liMySQL',
    },
    11: {
        skill: 'Sequelize',
        pic: './assets/images/skills/Sequelize.svg',
        link: 'http://docs.sequelizejs.com/',
        listClass: 'liSequelize',
    },
    12: {
        skill: 'Firebase',
        pic: './assets/images/skills/Firebase.png',
        link: 'https://firebase.google.com/',
        listClass: 'liFirebase',
    },
    13: {
        skill: 'Mocha',
        pic: './assets/images/skills/Mocha.png',
        link: 'https://mochajs.org/',
        listClass: 'liMocha',
    },
    14: {
        skill: 'Chai',
        pic: './assets/images/skills/chai.png',
        link: 'https://www.chaijs.com/',
        listClass: 'liChai',
    },
    15: {
        skill: 'Express',
        pic: './assets/images/skills/ExpressJs.png',
        link: 'https://expressjs.com/',
        listClass: 'liExpress',
    },
    16: {
        skill: 'Inquirer',
        pic: './assets/images/skills/inquirerJs.png',
        link: 'https://www.npmjs.com/package/inquirer',
        listClass: 'liInquirer',
    },
    17: {
        skill: 'Bootstrap 4',
        pic: './assets/images/skills/bootstrap4.png',
        link: 'https://getbootstrap.com/',
        listClass: 'liGit',
    },
    18: {
        skill: 'Git',
        pic: './assets/images/skills/git.png',
        link: 'https://git-scm.com/',
        listClass: 'liGit',
    },
    19: {
        skill: 'GitHub',
        pic: './assets/images/skills/github.png',
        link: 'https://github.com/',
        listClass: 'liGitHub',
    },
    20: {
        skill: 'VSCode',
        pic: './assets/images/skills/VSCode.png',
        link: 'https://code.visualstudio.com/',
        listClass: 'liVSCode',
    },
}