const skills ={
    1: {
        skill: 'HTML5',
        pic: './assets/images/skills/HTML5.png',
        link: '',
        listClass: 'liHTML5',
    },
    2: {
        skill: 'CSS3',
        pic: './assets/images/skills/CSS3.png',
        link: '',
        listClass: 'liCSS3',
    },
    3: {
        skill: 'ES6',
        pic: './assets/images/skills/ES6.png',
        link: '',
        listClass: 'liES6',
    },
    4: {
        skill: 'NodeJs',
        pic: './assets/images/skills/NodeJs.png',
        link: '',
        listClass: 'liNodeJs',
    },
    5: {
        skill: 'npm',
        pic: './assets/images/skills/npm.png',
        link: '',
        listClass: 'liNPM',
    },
    6: {
        skill: 'React',
        pic: './assets/images/skills/ReactJs.png',
        link: '',
        listClass: 'liReact',
    },
    7: {
        skill: 'jQuery',
        pic: './assets/images/skills/jQuery.png',
        link: '',
        listClass: 'lijQuery',
    },
    8: {
        skill: 'MongoDB',
        pic: './assets/images/skills/MongoDB.png',
        link: '',
        listClass: 'liMongoDB',
    },
    9: {
        skill: 'Mongoose',
        pic: './assets/images/skills/Mongoose.png',
        link: '',
        listClass: 'liMongoose',
    },
    10: {
        skill: 'MySQL',
        pic: './assets/images/skills/MySQL.png',
        link: '',
        listClass: 'liMySQL',
    },
    11: {
        skill: 'Sequelize',
        pic: './assets/images/skills/Sequelize.svg',
        link: '',
        listClass: 'liSequelize',
    },
    12: {
        skill: 'Firebase',
        pic: './assets/images/skills/Firebase.png',
        link: '',
        listClass: 'liFirebase',
    },
    13: {
        skill: 'Mocha',
        pic: './assets/images/skills/Mocha.png',
        link: '',
        listClass: 'liMocha',
    },
    14: {
        skill: 'Chai',
        pic: './assets/images/skills/chai.png',
        link: '',
        listClass: 'liChai',
    },
    15: {
        skill: 'Express',
        pic: './assets/images/skills/ExpressJs.png',
        link: '',
        listClass: 'liExpress',
    },
    16: {
        skill: 'Inquirer',
        pic: './assets/images/skills/inquirerJs.png',
        link: '',
        listClass: 'liInquirer',
    },
    17: {
        skill: 'Git',
        pic: './assets/images/skills/git.png',
        link: '',
        listClass: 'liGit',
    },
    18: {
        skill: 'Bootstrap 4',
        pic: './assets/images/skills/bootstrap4.png',
        link: '',
        listClass: 'liGit',
    },
    19: {
        skill: 'GitHub',
        pic: './assets/images/skills/github.png',
        link: '',
        listClass: 'liGitHub',
    },
    20: {
        skill: 'VSCode',
        pic: './assets/images/skills/VSCode.png',
        link: '',
        listClass: 'liVSCode',
    },
}